### PR TITLE
Fix bug with `limit_choices_to`

### PR DESCRIPTION
**Pull request by browniebroke**
Refs #94

### CODE REVIEW

**Comment by browniebroke** [comment]
@danielvdp @jieter bumping this in case you missed it. Let me know if there is anything missing on my end.

**Comment by jieter** [comment]
@browniebroke Thanks for the bump, I'll look into it today.

**Comment by jieter** [comment]
looks good, thanks! @browniebroke

**Comment by jieter** [comment]
released [0.7.5](https://pypi.python.org/pypi/django-modeltrans/0.7.5)

**Pull request merged**
