### PR TITLE
Fix translated form labels using current language

### LINKED ISSUE #87: Translation of form labels in admin is not correct
Appending the language is not lazy, so it results in the english translation being used.

https://github.com/zostera/django-modeltrans/blob/17967047be2b8462181ce4296b2ee733cadc23ba/modeltrans/fields.py#L89

### PR DESCRIPTION
**Pull request by julianwachholz**
Now forms will correctly use the current language's translation for a form label (or verbose name, etc.)

Fixes #87

### CODE REVIEW

**Comment by RobKuipers** [comment]
Tested; works like a charm. Hope this can be merged and released soon.

**Review by jieter — COMMENTED** [review]
Looks good, can you add a test to check behaviour?

**Comment by julianwachholz** [comment]
Thank you for the review @jieter - I've added a thorough test case that shows the proper translated labels being used in a model form.

**Comment by jieter** [comment]
Thanks @julianwachholz

**Pull request merged**
