### PR TITLE
Fix OperationalError under Django 5+

### PR DESCRIPTION
**Pull request by julianwachholz**
In earlier versions it would raise ProgrammingError.

### CODE REVIEW

**Comment by jieter** [comment]
The tests fail with `django.db.utils.NotSupportedError: PostgreSQL 14 or later is required (found 13.13).`, we should change the CI config to use a more recent postgres version. 
I'll ask you to rebase this PR after I did that.

**Comment by jieter** [comment]
#122 Is merged, please rebase.

**Comment by julianwachholz** [comment]
Good idea! Maybe in the future SQLite could also be included in the test matrix? 

I rebased this branch and #109

**Comment by jieter** [comment]
> Good idea! Maybe in the future SQLite could also be included in the test matrix?
> 

Nice idea, not sure if we actually support SQLite though, PR welcome!

> I rebased this branch and #109

Thanks!

**Comment by julianwachholz** [comment]
> Nice idea, not sure if we actually support SQLite though, PR welcome!

Yes! In fact I made some local changes to be able to run the test suite against it, as it's easier than spinning up a database. 

If you're open to it I can also propose some changes to make development on this package a little easier in that regard. E.g. a simple `compose.yml` that can spin up the required postgres db in a container.

**Comment by jieter** [comment]
> If you're open to it I can also propose some changes to make development on this package a little easier in that regard. E.g. a simple `compose.yml` that can spin up the required postgres db in a container.

I started work for this package before I was used to using docker compose. I'm glad to merge a simple example to ease development!

**Pull request merged**
