### PR TITLE
(FEATURE) add option for i18n model fields inheritance

### PR DESCRIPTION
**Pull request by dfirst**
Add i18n_fields to override TranslationField.fields in child models.

### CODE REVIEW

**Comment by jieter** [comment]
I see the use case, but I'm not sure if this is worth it.

Your proposed `i18n_fields = ["title", "body", "seo_title"]` is a little shorther than `i18n = TranslationField(fields=("title", "body", "seo_title"))`, but not by much and it adds a second way of doing things, which makes the API more complex from a users perspective.

**Comment by dfirst** [comment]
> I see the use case, but I'm not sure if this is worth it.
> 
> Your proposed `i18n_fields = ["title", "body", "seo_title"]` is a little shorther than `i18n = TranslationField(fields=("title", "body", "seo_title"))`, but not by much and it adds a second way of doing things, which makes the API more complex from a users perspective.

i18n = TranslationField(fields=("title", "body", "seo_title")) - this adding new field to database and will cause fields clashes exception, so it cant be used with child models.

To support TranslationField for child models we need to make it work like TranslatedVirtualField or some kind of proxy on child models i think this way is too complex. 

Have also an idea about to add i18n_kwargs attribute to have an option for overriding all TranslationField attrs in child model not just i18n fieldsset.

**Comment by jieter** [comment]
I have been thinking about this, I actually like your last suggestion:

> Have also an idea about to add `i18n_kwargs` attribute to have an option for overriding all TranslationField attrs in child model not just i18n `fields`set.

Please amend your patch accordingly.

**Comment by jieter** [comment]
@dfirst the current test failures are the result of a pip update, I applied this workaround patch in another project: https://github.com/jieter/django-tables2/commit/c7bdcaffffa6dc25c3fa70b17ebde855c8fb3b16

**Comment by dfirst** [comment]
> @dfirst the current test failures are the result of a pip update, I applied this workaround patch in another project: [jieter/django-tables2@c7bdcaf](https://github.com/jieter/django-tables2/commit/c7bdcaffffa6dc25c3fa70b17ebde855c8fb3b16)

Thank looks like now tests are running.

**Comment by dfirst** [comment]
I decide to name the attr as "i18n_field_params", it`s feels like more clear then just i18n_kwargs.

Also had idea about "i18n_field_kwargs".

**Comment by jieter** [comment]
Implementation looks good now. Can you also write documentation for this feature?

**Comment by dfirst** [comment]
Added docs.

**Comment by jieter** [comment]
@dfirst thanks, merged. I'll apply some minor fixes to the docs in a later commit.

**Pull request merged**
